---
title: "moneta"
author: "Rokas Aleksandravicius"
date: "October 20, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Tarkime metama moneta. Jeigu iškrenta herbas, tai laimite 12 EUR. Jeigu skaičius, tai pralošiate 10 EUR. Bus žaidžiama 100 kartų ir gauti rezultatai sumuojami.

Kokia tikimybė jums turėti teigiamą balansą po 100 kartų?

```{r}
n = 10^5
bal = c(rep(0, times = n))
teig_bal = c(rep(0, times = n))

for(i in 1:n){
  bal[i] = sum(sample(c(-10, 12), 100, replace = TRUE))

  if(bal[i] > 0){
    teig_bal[i] = 1
  }
  else{
    teig_bal[i] = 0
  }
}

mean(teig_bal)
```

Koks balanso pasikliautinis $95%$ intervalas? Apatinis ir viršutinis pasikliautinojo intervalo rėžiai:

```{r}
apatinis = mean(bal) - qt(0.975, df=n-1)*(sd(bal)/sqrt(n))
virsutinis = mean(bal) + qt(0.975, df=n-1)*(sd(bal)/sqrt(n))
apatinis
virsutinis
```

Kaip atrodo balanso tankis?
```{r}
plot(density(bal), main="Balanso tankis")
```

Naudotasi Raigardo darbu
